// In-memory fallback data store with Indian Rupee (₹) rates & localized locations
export const memoryStore = {
  users: [
    {
      _id: 'usr_seeker_1',
      name: 'Rohan Sharma',
      email: 'seeker@jobnest.com',
      password: '$2a$10$wN9F/9t6ZJ0d4aZ0g0g0g.1234567890abcdef',
      role: 'seeker',
      phone: '+91 98765 43210',
      location: 'Indiranagar, Bengaluru',
      bio: 'College student looking for flexible weekend & evening part-time shifts.',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      savedJobs: ['job_1', 'job_3']
    },
    {
      _id: 'usr_employer_1',
      name: 'Priya Nair',
      email: 'employer@jobnest.com',
      password: '$2a$10$wN9F/9t6ZJ0d4aZ0g0g0g.1234567890abcdef',
      role: 'employer',
      phone: '+91 91234 56789',
      location: 'Koramangala, Bengaluru',
      bio: 'Operations Head at Artisan Roastery Cafe & Local Retail Network.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      savedJobs: []
    }
  ],
  jobs: [
    {
      _id: 'job_1',
      title: 'Weekend Barista & Shift Associate',
      company: 'Third Wave Coffee',
      employer: 'usr_employer_1',
      category: 'Cafe & Barista',
      hourlyRate: 250,
      shiftTiming: 'Weekend Special',
      hoursPerWeek: 16,
      locationName: '100ft Road, Indiranagar, Bengaluru',
      coordinates: { lat: 12.9784, lng: 77.6408 },
      distanceKm: 0.8,
      description: 'Looking for an enthusiastic weekend barista to prepare espresso beverages, manage customer order flow, and assist store operations.',
      requirements: ['Basic coffee/beverage knowledge', 'Good communication in English/Kannada', 'Punctual & team-oriented'],
      perks: ['Free gourmet beverage per shift', 'Performance incentives', 'Flexible weekend rosters'],
      positionsAvailable: 2,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_2',
      title: 'Evening Retail Store Representative',
      company: 'FabIndia Experience Center',
      employer: 'usr_employer_1',
      category: 'Retail & Store',
      hourlyRate: 200,
      shiftTiming: 'Evening (6PM - 11PM)',
      hoursPerWeek: 15,
      locationName: 'Connaught Place, New Delhi',
      coordinates: { lat: 28.6315, lng: 77.2167 },
      distanceKm: 1.5,
      description: 'Assist walk-in store visitors with product inquiries, restock retail shelves, and manage checkout queues during peak evening hours.',
      requirements: ['Friendly customer interaction', 'Punctual attendance', 'Basic POS billing awareness'],
      perks: ['20% store employee discount', 'Travel allowance for late shifts'],
      positionsAvailable: 3,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_3',
      title: 'Express Parcel Delivery Partner',
      company: 'Shadowfax Express',
      employer: 'usr_employer_1',
      category: 'Delivery & Logistics',
      hourlyRate: 320,
      shiftTiming: 'Flexible',
      hoursPerWeek: 20,
      locationName: 'HSR Layout Sector 3, Bengaluru',
      coordinates: { lat: 12.9116, lng: 77.6389 },
      distanceKm: 2.2,
      description: 'Deliver e-commerce parcels and local packages within your assigned neighborhood hub using two-wheelers or e-bikes.',
      requirements: ['Valid DL / EV bike access', 'Smartphone with GPS navigation', 'Familiarity with neighborhood routes'],
      perks: ['Weekly payouts', 'Fuel/charge subsidy', 'Keep 100% of customer tips'],
      positionsAvailable: 5,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_4',
      title: 'Class 9-12 Mathematics Tutor',
      company: 'BrightAcademy Classes',
      employer: 'usr_employer_1',
      category: 'Tutoring & Education',
      hourlyRate: 450,
      shiftTiming: 'Afternoon (1PM - 6PM)',
      hoursPerWeek: 10,
      locationName: 'Jubilee Hills, Hyderabad',
      coordinates: { lat: 17.4319, lng: 78.4074 },
      distanceKm: 3.1,
      description: 'Conduct small-group problem-solving sessions for high school students in Algebra, Trigonometry, and Board exam prep.',
      requirements: ['Strong math background (B.Sc / B.Tech pursuing)', 'Patient teaching approach'],
      perks: ['High hourly payout', 'Study material provided', 'Flexible shift timings'],
      positionsAvailable: 2,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_5',
      title: 'Live Music & Food Fest Crew',
      company: 'Sunburn Arena Events',
      employer: 'usr_employer_1',
      category: 'Event Staff',
      hourlyRate: 380,
      shiftTiming: 'Weekend Special',
      hoursPerWeek: 14,
      locationName: 'Bandra Reclamation, Mumbai',
      coordinates: { lat: 19.0544, lng: 72.8258 },
      distanceKm: 4.0,
      description: 'Join the festival execution crew for ticketing verification, crowd direction, VIP lounge assistance, and stage support.',
      requirements: ['Energetic personality', 'Good team communication'],
      perks: ['Free event crew pass', 'Catered food & snacks', 'Official festival tee'],
      positionsAvailable: 8,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_6',
      title: 'Part-Time Front Desk Associate',
      company: 'WeWork Cyber Hub',
      employer: 'usr_employer_1',
      category: 'Office & Admin',
      hourlyRate: 280,
      shiftTiming: 'Morning (8AM - 1PM)',
      hoursPerWeek: 15,
      locationName: 'DLF Cyber City, Gurugram',
      coordinates: { lat: 28.4950, lng: 77.0895 },
      distanceKm: 1.2,
      description: 'Manage community check-in desk, coordinate meeting room bookings, and handle visitor queries in a modern co-working space.',
      requirements: ['Basic computer proficiency', 'Polite phone etiquette'],
      perks: ['Free co-working hot desk access', 'Unlimited coffee & tea', 'Corporate networking'],
      positionsAvailable: 1,
      status: 'active',
      createdAt: new Date().toISOString()
    }
  ],
  applications: [
    {
      _id: 'app_1',
      job: 'job_1',
      applicant: 'usr_seeker_1',
      coverNote: 'I am a student at NIFT nearby and available every Saturday & Sunday.',
      availability: 'Immediate (Saturdays & Sundays)',
      phone: '+91 98765 43210',
      status: 'Applied',
      createdAt: new Date(Date.now() - 86400000).toISOString()
    }
  ]
};
