// In-memory fallback data store centered in Kottayam Town, Kerala with Indian Rupee (₹) rates
export const memoryStore = {
  users: [
    {
      _id: 'usr_seeker_1',
      name: 'Rohan Sharma',
      email: 'seeker@jobnest.com',
      password: '$2a$10$wN9F/9t6ZJ0d4aZ0g0g0g.1234567890abcdef',
      role: 'seeker',
      phone: '+91 98765 43210',
      location: 'Kottayam Town, Kerala',
      bio: 'College student in Kottayam looking for flexible weekend & evening part-time shifts.',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      savedJobs: ['job_1', 'job_3']
    },
    {
      _id: 'usr_employer_1',
      name: 'Priya Nair',
      email: 'employer@jobnest.com',
      password: '$2a$10$wN9F/9t6ZJ0d4aZ0g0g0g.1234567890abcdef',
      role: 'employer',
      phone: '+91 91234 56789',
      location: 'Kanjikuzhy, Kottayam',
      bio: 'Recruiter at Local Cafe & Retail Networks in Kottayam Town.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      savedJobs: []
    }
  ],
  jobs: [
    {
      _id: 'job_1',
      title: 'Weekend Barista & Counter Staff',
      company: 'Highland Roasters Cafe',
      employer: 'usr_employer_1',
      category: 'Cafe & Barista',
      hourlyRate: 250,
      shiftTiming: 'Weekend Special',
      hoursPerWeek: 16,
      locationName: 'Kanjikuzhy Junction, Kottayam Town',
      coordinates: { lat: 9.5916, lng: 76.5330 },
      distanceKm: 0.8,
      description: 'Looking for an energetic weekend barista to brew coffees, take guest orders, and assist store operations near Kanjikuzhy.',
      requirements: ['Basic beverage preparation', 'Communication in Malayalam/English', 'Punctual & polite'],
      perks: ['Free beverage per shift', 'Performance tips', 'Flexible weekend rosters'],
      positionsAvailable: 2,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_2',
      title: 'Evening Retail Store Associate',
      company: 'Textile World Mart',
      employer: 'usr_employer_1',
      category: 'Retail & Store',
      hourlyRate: 220,
      shiftTiming: 'Evening (6PM - 11PM)',
      hoursPerWeek: 15,
      locationName: 'Thirunakkara Bus Stand Road, Kottayam',
      coordinates: { lat: 9.5890, lng: 76.5210 },
      distanceKm: 1.2,
      description: 'Assist shoppers during peak evening hours, restock store displays, and manage customer checkout.',
      requirements: ['Friendly customer handling', 'Punctual attendance', 'Basic billing awareness'],
      perks: ['15% employee discount', 'Travel allowance for late evening shifts'],
      positionsAvailable: 3,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_3',
      title: 'Express Parcel Delivery Partner',
      company: 'Kottayam Express Logistics',
      employer: 'usr_employer_1',
      category: 'Delivery & Logistics',
      hourlyRate: 300,
      shiftTiming: 'Flexible',
      hoursPerWeek: 20,
      locationName: 'Collectorate Road, Kottayam Town',
      coordinates: { lat: 9.5950, lng: 76.5260 },
      distanceKm: 2.0,
      description: 'Deliver e-commerce parcels and local packages across Kottayam Town and nearby residential areas.',
      requirements: ['Two-wheeler or scooter with valid license', 'Smartphone with GPS navigation'],
      perks: ['Weekly direct bank payouts', 'Fuel allowance', 'Keep 100% of tips'],
      positionsAvailable: 5,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_4',
      title: 'Class 9-12 Physics & Maths Tutor',
      company: 'CMS Academic Tuition Hub',
      employer: 'usr_employer_1',
      category: 'Tutoring & Education',
      hourlyRate: 450,
      shiftTiming: 'Afternoon (1PM - 6PM)',
      hoursPerWeek: 10,
      locationName: 'CMS College Road, Kottayam',
      coordinates: { lat: 9.5980, lng: 76.5180 },
      distanceKm: 2.8,
      description: 'Teach small batches of high school students in Mathematics & Physics with focus on Board Exam preparation.',
      requirements: ['B.Tech / B.Sc student or graduate', 'Clear concept explanations'],
      perks: ['High hourly payout', 'Quiet tuition center environment', 'Flexible shift timings'],
      positionsAvailable: 2,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_5',
      title: 'Cultural Fest & Event Crew',
      company: 'Kottayam Youth Events',
      employer: 'usr_employer_1',
      category: 'Event Staff',
      hourlyRate: 350,
      shiftTiming: 'Weekend Special',
      hoursPerWeek: 14,
      locationName: 'Nehru Stadium Grounds, Kottayam',
      coordinates: { lat: 9.5850, lng: 76.5290 },
      distanceKm: 3.5,
      description: 'Join event management crew for entry ticket checking, crowd coordination, and stage support during weekend fests.',
      requirements: ['Energetic personality', 'Good communication skills'],
      perks: ['Free event crew entry', 'Food & snacks provided', 'Event certificate'],
      positionsAvailable: 8,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_6',
      title: 'Co-Working Desk & Reception Support',
      company: 'Nagampadam Office Hub',
      employer: 'usr_employer_1',
      category: 'Office & Admin',
      hourlyRate: 280,
      shiftTiming: 'Morning (8AM - 1PM)',
      hoursPerWeek: 15,
      locationName: 'Nagampadam Railway Station Area, Kottayam',
      coordinates: { lat: 9.6010, lng: 76.5280 },
      distanceKm: 1.5,
      description: 'Manage morning visitor desk, assist members with conference room bookings, and support office administrative tasks.',
      requirements: ['Basic computer skills', 'Pleasant communication style'],
      perks: ['Free Wi-Fi co-working desk access', 'Unlimited coffee', 'Networking opportunities'],
      positionsAvailable: 1,
      status: 'active',
      createdAt: new Date().toISOString()
    }
  ],
  applications: [
    {
      _id: 'app_1',
      job: 'job_1',
      applicant: 'usr_seeker_1',
      coverNote: 'I live nearby in Kottayam Town and available for weekend shifts.',
      availability: 'Immediate (Saturdays & Sundays)',
      phone: '+91 98765 43210',
      status: 'Applied',
      createdAt: new Date(Date.now() - 86400000).toISOString()
    }
  ]
};
