// In-memory fallback data store centered in Kochi, Kerala with Indian Rupee (₹) rates
export const memoryStore = {
  users: [
    {
      _id: 'usr_seeker_1',
      name: 'Rohan Sharma',
      email: 'seeker@jobnest.com',
      password: '$2a$10$wN9F/9t6ZJ0d4aZ0g0g0g.1234567890abcdef',
      role: 'seeker',
      phone: '+91 98765 43210',
      location: 'Marine Drive, Kochi, Kerala',
      bio: 'College student in Kochi looking for flexible weekend & evening part-time shifts.',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
      savedJobs: ['job_1', 'job_3']
    },
    {
      _id: 'usr_employer_1',
      name: 'Priya Nair',
      email: 'employer@jobnest.com',
      password: '$2a$10$wN9F/9t6ZJ0d4aZ0g0g0g.1234567890abcdef',
      role: 'employer',
      phone: '+91 91234 56789',
      location: 'Panampilly Nagar, Kochi',
      bio: 'Recruiter at Artisan Brews & Retail Networks in Ernakulam, Kochi.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      savedJobs: []
    }
  ],
  jobs: [
    {
      _id: 'job_1',
      title: 'Weekend Barista & Counter Staff',
      company: 'Cafe De Port',
      employer: 'usr_employer_1',
      category: 'Cafe & Barista',
      hourlyRate: 250,
      shiftTiming: 'Weekend Special',
      hoursPerWeek: 16,
      locationName: 'Marine Drive Walkway, Kochi',
      coordinates: { lat: 9.9790, lng: 76.2750 },
      distanceKm: 0.8,
      description: 'Looking for a friendly weekend barista to brew coffees, take guest orders, and maintain counter hygiene along Marine Drive.',
      requirements: ['Basic beverage preparation', 'Communication in Malayalam/English', 'Punctual & polite'],
      perks: ['Free gourmet beverage per shift', 'Performance tips', 'Flexible weekend rosters'],
      positionsAvailable: 2,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_2',
      title: 'Evening Store Sales Representative',
      company: 'LuLu Hypermarket Store',
      employer: 'usr_employer_1',
      category: 'Retail & Store',
      hourlyRate: 220,
      shiftTiming: 'Evening (6PM - 11PM)',
      hoursPerWeek: 15,
      locationName: 'LuLu Mall, Edappally, Kochi',
      coordinates: { lat: 10.0270, lng: 76.3080 },
      distanceKm: 1.5,
      description: 'Assist shoppers during peak evening hours, restock retail section displays, and assist customer checkout.',
      requirements: ['Friendly customer handling', 'Punctual attendance', 'Basic billing awareness'],
      perks: ['15% employee store discount', 'Travel allowance for late evening shifts'],
      positionsAvailable: 3,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_3',
      title: 'Express Parcel Delivery Partner',
      company: 'Kochi Express Deliveries',
      employer: 'usr_employer_1',
      category: 'Delivery & Logistics',
      hourlyRate: 300,
      shiftTiming: 'Flexible',
      hoursPerWeek: 20,
      locationName: 'InfoPark Road, Kakkanad, Kochi',
      coordinates: { lat: 10.0100, lng: 76.3600 },
      distanceKm: 2.2,
      description: 'Deliver e-commerce parcels and local document packages across Kakkanad and InfoPark tech zones.',
      requirements: ['Two-wheeler or scooter with valid license', 'Smartphone with GPS app'],
      perks: ['Weekly direct bank payouts', 'Fuel allowance', 'Keep 100% of tips'],
      positionsAvailable: 5,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_4',
      title: 'Class 9-12 Physics & Maths Tutor',
      company: 'Panampilly Learning Hub',
      employer: 'usr_employer_1',
      category: 'Tutoring & Education',
      hourlyRate: 450,
      shiftTiming: 'Afternoon (1PM - 6PM)',
      hoursPerWeek: 10,
      locationName: 'Main Avenue, Panampilly Nagar, Kochi',
      coordinates: { lat: 9.9620, lng: 76.2930 },
      distanceKm: 3.0,
      description: 'Teach small batches of high school students in Mathematics & Physics with focus on Board Exam preparation.',
      requirements: ['B.Tech / B.Sc student or graduate', 'Clear concept explanations'],
      perks: ['High hourly payout', 'Quiet study center environment', 'Flexible shift timings'],
      positionsAvailable: 2,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_5',
      title: 'Heritage Fest & Concert Event Crew',
      company: 'Fort Kochi Cultural Events',
      employer: 'usr_employer_1',
      category: 'Event Staff',
      hourlyRate: 350,
      shiftTiming: 'Weekend Special',
      hoursPerWeek: 14,
      locationName: 'Vasco da Gama Square, Fort Kochi',
      coordinates: { lat: 9.9670, lng: 76.2440 },
      distanceKm: 4.2,
      description: 'Join event management crew for entry ticket checking, crowd coordination, and stage management during weekend fests.',
      requirements: ['Energetic personality', 'Good communication skills'],
      perks: ['Free event crew entry', 'Food & snacks provided', 'Event certificate'],
      positionsAvailable: 8,
      status: 'active',
      createdAt: new Date().toISOString()
    },
    {
      _id: 'job_6',
      title: 'Co-Working Desk & Reception Support',
      company: 'WorkSpace InfoPark',
      employer: 'usr_employer_1',
      category: 'Office & Admin',
      hourlyRate: 280,
      shiftTiming: 'Morning (8AM - 1PM)',
      hoursPerWeek: 15,
      locationName: 'InfoPark Phase 1, Kakkanad, Kochi',
      coordinates: { lat: 10.0120, lng: 76.3630 },
      distanceKm: 1.8,
      description: 'Manage morning visitor desk, assist members with conference room bookings, and support office administrative tasks.',
      requirements: ['Basic computer skills', 'Pleasant communication style'],
      perks: ['Free high-speed Wi-Fi co-working space access', 'Unlimited coffee', 'Tech community networking'],
      positionsAvailable: 1,
      status: 'active',
      createdAt: new Date().toISOString()
    }
  ],
  applications: [
    {
      _id: 'app_1',
      job: 'job_1',
      applicant: 'usr_seeker_1',
      coverNote: 'I live nearby on Marine Drive and available for weekend shifts.',
      availability: 'Immediate (Saturdays & Sundays)',
      phone: '+91 98765 43210',
      status: 'Applied',
      createdAt: new Date(Date.now() - 86400000).toISOString()
    }
  ]
};
